
services:
  wallet_db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env_files/.env.db
    ports:
      - '5438:5432'
    restart: always
  app:
    build:
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate && 
      gunicorn --workers 3 --threads 2 core.wsgi:application --bind 0.0.0.0:8000 
      & celery -A core worker -l INFO"
    expose:
      - '8000'
    restart: always
    volumes:
      - django_logs:/app/logs
    depends_on:
      - wallet_db
      - redis
    env_file:
      - env_files/.env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
  redis:
    image: redis
    restart: always
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx
    ports:
      - '1337:80'
    depends_on:
      - app
    restart: always

volumes:
  postgres_data:
  django_logs:
  redis-data:

