# Generated by Django 5.1.5 on 2025-01-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2,
                                                default=0,
                                                max_digits=10)),
            ],
        ),
    ]
